### ISSUE TITLE
{Closed}

### ISSUE THREAD

**Issue by ghost** [popey/sosumi-snap#16]
When I launch sosumi I have a problem with kvm module, what can I do ?
```
sosumi
realpath: '': No such file or directory
*** Checking for kvm interface connection
INFO: kvm interface is connected
*** Checking for firmware files
*** Checking for Base System files
*** Checking for disk image
*** Checking for launch script
*** Launch!
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize KVM: Permission denied

```

**Comment by mrwillbarnz** [comment]
Hi @Leo-Qwant,

Firstly, I'd double-check if Virtualization is enabled on your machine and the relevant _libvirt_ _qemu_ and _virt-manager_ (optional) packages are installed and your user is correctly assigned to the _kvm_ and _libvirt_ groups. Log out/Log back in to apply the group changes. Then, try invoking the command `virsh --list all` to double-check the permissions are correctly set.

For further information for Ubuntu look here, the Wiki also has detailed commands for modifying your group permissions: [KVM_Ubuntu_Docs](https://help.ubuntu.com/community/KVM/Installation#Installation_of_KVM)

I'd secondly double-check if the snap-package can access the kvm interface by running `snap connections sosumi` and then `snap interface sosumi`, this lists whether sosumi has access to kvm.

Now try running _sosumi_ again!

Hope this helps :)

**Comment by VincentCCandela** [comment]
I had this same problem. When I ran ```virsh --list all```, it said that virsh was not found so I did ```sudo apt install libvirt-clients
```. For connections, this is what I got: 
Interface               Plug                           Slot                     Notes
audio-playback          sosumi:audio-playback          :audio-playback          -
audio-record            sosumi:audio-record            -                        -
desktop                 sosumi:desktop                 :desktop                 -
home                    sosumi:home                    :home                    -
kvm                     sosumi:kvm                     :kvm                     -
network                 sosumi:network                 :network                 -
network-bind            sosumi:network-bind            :network-bind            -
network-control         sosumi:network-control         -                        -
opengl                  sosumi:opengl                  :opengl                  -
raw-usb                 sosumi:raw-usb                 -                        -
screen-inhibit-control  sosumi:screen-inhibit-control  :screen-inhibit-control  -
unity7                  sosumi:unity7                  :unity7                  -
wayland                 sosumi:wayland                 :wayland                 -
x11                     sosumi:x11                     :x11                     -
.

This is what happened when I tried to run sosumi again:

vincent@device:~$ sosumi
*** Checking for kvm interface connection
INFO: kvm interface is connected
*** Checking for firmware files
*** Checking for Base System files
*** Checking for disk image
*** Checking for launch script
*** Launch!
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize KVM: Permission denied

Thank you in advance to whoever knows whats going wrong.

**Comment by VincentCCandela** [comment]
I found the fix. Source :https://www.how2shout.com/how-to/sosumi-an-easy-way-to-install-macos-on-ubuntu-linux-but-didnt-work.html
 1) Remove sosumi regular and install sosumi edge: ```snap remove sosumi``` and ```snap install sosumi --edge```
2) Run these commands ```xhost```, ```xhost local:```, and ``` xhost localhost```
