### ISSUE TITLE
Is it safe to upgrade insides the VM?

### ISSUE THREAD

**Issue by BDHU** [popey/sosumi-snap#17]
Or should we simply wait for the snap update?

**Comment by ayr-ton** [comment]
@BDHU What did you discover?

**Comment by BDHU** [comment]
@ayr-ton I haven't tried to upgrade the OS insides snap. I believe it's not recommended but it might worth trying

**Comment by ayr-ton** [comment]
I made a backup and tried. After downloading the new boot option (which is the new installer) is unable to boot.
