### ISSUE TITLE
Improve guest video memory

### ISSUE THREAD

**Issue by superbonaci** [popey/sosumi-snap#18]
I'm trying to play a couple of movies which I've purchased from iTunes, but video is black. I've realized that video ram is only 3MB in size. Can this be changed?

**Comment by tv0ll** [comment]
Videos work fine for me. Is this still not working for you?

**Comment by kriptonian1** [comment]
> Videos work fine for me. Is this still not working for you?

it is not working for me too, there no clear guid here like this https://github.com/foxlet/macOS-Simple-KVM/tree/master/docs
and also _**the community is not that active**_, but the concept is good.

**Comment by superbonaci** [comment]
Will try again when the virtual machine gets updated to macOS Big Sur.

**Comment by ayr-ton** [comment]
Also waiting for the update

**Comment by superbonaci** [comment]
Finally ditched `sosumi-snap`, now I'm running https://github.com/foxlet/macOS-Simple-KVM and perfect with Big Sur. Of course still same issue with video memory but that's a different story.
