### ISSUE TITLE
Give sosumi VM more ram.

### ISSUE THREAD

**Issue by RKDUDE02** [popey/sosumi-snap#27]
Hi! I managed to get this up and running and i was surprised by how easy it was! When i go to about this mac i notice that it only has 2 GB of ram. Is there a way to give it more ram?

**Comment by RKDUDE02** [comment]
I found out how to give it more ram. Open your file manager and open your home folder. Select snap folder. Select sosumi. Select common. And open launch.sh with a text editor.

 #!/bin/bash

OSK="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"

"$SNAP"/usr/bin/qemu-system-x86_64 \
    -enable-kvm \
    -m 2G \
    -machine q35,accel=kvm \
    -smp 4,cores=2 \
    -cpu Penryn,vendor=GenuineIntel,kvm=on,+sse3,+sse4.2,+aes,+xsave,+avx,+xsaveopt,+xsavec,+xgetbv1,+avx2,+bmi2,+smep,+bmi1,+fma,+movbe,+invtsc \
    -device isa-applesmc,osk="$OSK" \
    -smbios type=2 \
    -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 \
    -serial mon:stdio \
    -drive if=pflash,format=raw,readonly,file="$SNAP"/firmware/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file="$SNAP_USER_COMMON"/firmware/OVMF_VARS-1024x768.fd \
    -device virtio-vga,virgl=on \
    -display sdl,gl=on \
    -L "$SNAP"/usr/share/seabios/ \
    -L "$SNAP"/usr/lib/ipxe/qemu/ \
    -audiodev pa,id=pa,server="/run/user/$(id -u)/pulse/native" \
    -device ich9-intel-hda -device hda-output,audiodev=pa \
    -usb -device usb-kbd -device usb-mouse \
    -netdev user,id=net0 \
    -device vmxnet3,netdev=net0,id=net0 \
    -drive id=ESP,if=virtio,format=qcow2,file="$SNAP_USER_COMMON"/ESP.qcow2 \
    -drive id=SystemDisk,if=virtio,file="$SNAP_USER_COMMON"/macos.qcow2 \

Now change the line that says -m 2G to -m 4G or to a custom amount.

**Comment by Zahrun** [comment]
You can also increase the number of cores to 4 if your host has 4+.
-smp 4,cores=2 
-smp 4,cores=4

**Comment by RKDUDE02** [comment]
> You can also increase the number of cores to 4 if your host has 4+.
> -smp 4,cores=2
> -smp 4,cores=4

Also a good point! If you need something a little faster

**Comment by hdihd9162** [comment]
in ubuntu i cant find common folder in sossumi i have current and 18
