### ISSUE TITLE
How install on wsl ? (with xlauch)

### ISSUE THREAD

**Issue by mateushnsoares** [popey/sosumi-snap#32]
I can open native programs with my WSL using xlaunch but when I run:
```sh
sudo snap install sosumi (or sosumi --edge)
```
result in this:
![image](https://user-images.githubusercontent.com/59037640/93216456-22142500-f73e-11ea-9276-e425b92b5af5.png)

**Comment by FarisZR** [comment]
install snap first.

i dont what distro you are using but try

'sudo apt install snapd'

**Comment by popey** [comment]
WSL doesn't (yet) support snaps. It might in the future, but that's not a bug for sosumi. Thanks for your interest though :)
