### ISSUE TITLE
Can Sosumi be available in non-Snap form?

### ISSUE THREAD

**Issue by ghost** [popey/sosumi-snap#35]
Even if it's an .AppImage, that would be really great! Many of us hate the centralised Snap store ecosystem, and use distros without snap such as Linux Mint.

(BTW, great name, took me ten minutes to see it.)

**Comment by FarisZR** [comment]
probably not since he works on snapcraft an ubuntu

**Comment by popey** [comment]
Of course it can be made in non-snap form. I'm not about to do that though.
