### ISSUE TITLE
Get rid of the terminal window

### ISSUE THREAD

**Issue by ahahn94** [popey/sosumi-snap#6]
Sosumi is launching in a terminal window, which stays open as long as the VM is running.
Having sosumi launch only the window containing the VM output (so, only one window instead of two) would be a nice improvement, as the additional window is always getting into ones way when using Alt + Tab.

**Comment by popey** [comment]
Yes, this is a good idea. I think longer term We should perhaps have a graphical launcher which allows settings to be tweaked.

Perhaps I could have two desktop files, one "Sosumi" which launches the emulator, and another "Sosumi Settings". Until then, people can launch in a terminal manually, or use the icon, which should not launch a terminal. I'll fix that, thanks.

**Comment by ahahn94** [comment]
Yeah, having two desktop files sounds like the way to go :+1: 

Thank you for the bugfix and the hard work you put into sosumi. It's really appreciated! :+1:
